---
run:
  concurency: 4
  deadline: 2m
  issues-exit-code: 1
  skip-files:
    - ".+_test.go"
    - "vendor/*"

linters-settings:
  lll:
    line-length: 140

  cyclop:
    max-complexity: 15

  funlen:
    lines: 70

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true

  disable:
    - errcheck
    - varnamelen
    - wsl
    - goconst
    - maligned
    - deadcode
    - ifshort
    - structcheck
    - varcheck
    - interfacer
    - golint
    - nosnakecase
    - scopelint
    - exhaustivestruct
    - revive
    - gci
    - godox
    - nlreturn
    - ireturn
    - tagliatelle
    - depguard
    - tagalign

  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 100
  max-same-issues: 4
  new: false

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: internal/controller/grpc/calendarv1/type_conversions.go
      linters:
        - unused

    - path: internal/model/error.go
      linters:
        - unused

    - linters:
        - stylecheck
      text: "ST1000:"
