apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplevault
  template:
    metadata:
      labels:
        app: samplevault
    spec:
      containers:
        - name: samplevault
          image: marcussss/simplevault:3c9bbb5
          ports:
            - containerPort: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
