apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplevault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplevault
  template:
    metadata:
      labels:
        app: samplevault
    spec:
      containers:
        - name: samplevault
          image: samplevault:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/read
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
