apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplevault
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  rules:
    - host: backend-service
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: samplevault
                port:
                  number: 8000
