apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tarantool
spec:
  selector:
    matchLabels:
      app: tarantool
  serviceName: "tarantool"
  replicas: 1
  template:
    metadata:
      labels:
        app: tarantool
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: tarantool
          image: tarantool/tarantool:2.10.8
          env:
            - name: "TARANTOOL_USER"
              value: "tarantool"
            - name: "TARANTOOL_PASSWORD"
              value: "tarantool"
            - name: "TARANTOOL_DATABASE"
              value: "tarantool"
          args: ["tarantool", "/opt/tarantool/app.lua"]
          ports:
            - containerPort: 3301
              name: bin
          volumeMounts:
            - name: data
              mountPath: /var/lib/tarantool
            - name: app
              mountPath: /opt/tarantool/app.lua
              subPath: app.lua
      volumes:
        - name: app
          configMap:
            name: app
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
