apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tarantool-statefulset
spec:
  serviceName: tarantool
  replicas: 1
  selector:
    matchLabels:
      app: tarantool
  template:
    metadata:
      labels:
        app: tarantool
    spec:
      containers:
        - name: samplevault-tarantool
          image: samplevault-tarantool:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: tarantool-pv
              mountPath: /tmp/tarantool
          args: [ "tarantool", "/home/ubuntu/samplevault/app.lua" ]
