apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tarantool-statefulset
spec:
  serviceName: tarantool
  replicas: 1
  selector:
    matchLabels:
      app: tarantool
  template:
    metadata:
      labels:
        app: tarantool
    spec:
      containers:
        - name: samplevault-tarantool
          image: samplevault-tarantool:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: data
              mountPath: /tmp/tarantool
          ports:
            - containerPort: 3301
          command: ["tarantool", "/home/ubuntu/samplevault/tar.lua"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
