apiVersion: v1
kind: PersistentVolume
metadata:
  name: tarantool-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/tarantool
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tarantool-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage

