apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  annotations:
    volume.beta.kubernetes.io/storage-class: "retain"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
