name: CD

on:
  push:

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repository
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
          SOURCE: .
          TARGET: /home/ubuntu/samplevault

  stop-old-start-new:
    needs: build-n-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd samplevault
            eval $(minikube docker-env)
            docker build -t "marcussss/samplevault:latest" -f "Dockerfile" .
            kubectl delete deploy --all
            kubectl delete service --all
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
            eval $(minikube docker-env -u)
