name: CD

on:
  push:

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repository
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
          SOURCE: .
          TARGET: /home/ubuntu/samplevault

  stop-old-start-new:
    needs: build-n-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd samplevault
            eval $(minikube docker-env)
            docker build -t "samplevault:latest" -f "Dockerfile" .
            kubectl delete deploy --all
            kubectl delete service --all
            kubectl delete ingress --all
            minikube addons enable ingress
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
            kubectl apply -f ingress.yml
            eval $(minikube docker-env -u)
#            export BACKEND_URL=$(minikube service samplevault --url)
#            echo "BACKEND_URL=$BACKEND_URL" > env_vars
#            source env_vars
#            envsubst < /etc/nginx/template/default > /tmp/nginx_updated.conf
#            sudo cp /tmp/nginx_updated.conf /etc/nginx/sites-enabled/default
#            sudo systemctl restart nginx
