name: CD

on:
  push:

jobs:
  copy-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repository
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_HOST: ${{ secrets.HOST }}
          SOURCE: .
          TARGET: /home/ubuntu/samplevault

  update-app-version:
    needs: copy-repository
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd samplevault
            kubectl create secret generic tarantool-secrets \
            --from-literal=TARANTOOL_USER=${{ secrets.TARANTOOL_USER }} \
            --from-literal=TARANTOOL_PASSWORD=${{ secrets.TARANTOOL_PASSWORD }} \
            --from-literal=TARANTOOL_DSN=${{ secrets.TARANTOOL_DSN }} \
            --from-literal=TARANTOOL_DATABASE=${{ secrets.TARANTOOL_DATABASE }}
            bash update_pods.sh
